### ISSUE TITLE
Authentication step 8 failed

### ISSUE THREAD

**Issue by 3SMMZRjWgS** [exploringfinance/rameritrade#10]
@exploringfinance, thanks for creating the package! Also understand that you won't make any changes till the Schwab integration and its impact on ToS API is clear. 

But I thought I would flag this one as I tried, but I was unable to get passed authentication in step 8. I ran the following:

```
td_auth_refreshToken("CONSUMERAUTHORIZATIONCODE", 
                                   "https://callbackURL", 
                                   "https://testing/?code=CONSUMERAUTHORIZATIONCODE")
```
The error message I received was the following:

`"Error: The auth code provided does not appear to be a valid auth code. Please confirm the URL link from a successful login was passed."`

I double checked for typos and there shouldn't be any. Any idea(s)?

**Comment by exploringfinance** [comment]
Try following the steps in this blog post:

https://exploringfinance.github.io/posts/2020-10-17-trade-on-td-ameritrade-with-r/

Best,
Tony

**Comment by causality-loop** [comment]
@3SMMZRjWgS Hi, you seem to have the authorization code (ie, `codeToken`) twice.  Try this:

```
refresh_token <- rameritrade::td_auth_refreshToken(
  consumerKey='CONSUMER_KEY',
  callbackURL='CALLBACK_URL',
  codeToken='AUTHORIZATION_CODE'
)

saveRDS(refresh_token, '/path/to/refreshToken.rds')
```

Where `consumerKey` is the same one from Step 5.

**Comment by 3SMMZRjWgS** [comment]
Thank you both for the help!

For others reference, Step 3 from Tony's [solution](https://github.com/exploringfinance/rameritrade/issues/10#issuecomment-1114365433) was what I missed. The authorization token needs to be copied and pasted from the browser once logged into TD's site via the URL generated from `td_auth_loginURL()`.
