### ISSUE TITLE
How to download option historical price? 

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [exploringfinance/rameritrade#7]
https://rdrr.io/cran/rameritrade/man/td_optionChain.html

I only see how to download the current price of options. Is there a way to get the historical prices of options via rameritrade?

**Comment by exploringfinance** [comment]
It does not appear that TD offers this capability after testing the API directly

**Comment by prRZ5F4LXZ** [comment]
Are you aware of any other free source other than tdameritrade that offers historical option quotes?

**Comment by exploringfinance** [comment]
Historical option data is massive in size. People pay a lot of money for it. Doubt anyone is giving it away for free unfortunately.
