### ISSUE TITLE
Order replacing

### ISSUE THREAD

**Issue by quantprofessor** [exploringfinance/rameritrade#9]
This is not an issue but a request for another function that can modify an existing order.

**Comment by exploringfinance** [comment]
I am not going to make any changes to the package at this time. The Schwab TD integration is nearing a completion and the fate of the API is unfortunately still in question. If the API makes it over to Schwab then I will absolutely make the update. 

You can also check out the documentation yourself and use the existing functions to build one:
https://developer.tdameritrade.com/account-access/apis/put/accounts/%7BaccountId%7D/orders/%7BorderId%7D-0
